### PR TITLE
Protein ortho

### PR DESCRIPTION
**Pull request by RedSnail**
I've added an option to choose method of pangenome building (now you can choose proteinortho instead of mmseqs), documented the changes and implemented unit tests

### CODE REVIEW

**Comment by oxygen311** [comment]
@asetGem could you please add this feature to the main PanACoTA repo?

Now we are working on pan-genomics and based on our experience proteinortho is more accurate in paralogues prediction.

**Comment by asetGem** [comment]
Hi there!
Could you please send me the link to proteinortho (or its publication) so that I can see how it works please?

Thanks!

**Comment by RedSnail** [comment]
> Hi there! Could you please send me the link to proteinortho (or its publication) so that I can see how it works please?
> 
> Thanks!

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-124

**Comment by asetGem** [comment]
Hi! Sorry for the delay, busy times...
Thank you for the suggestion of integrating proteinortho. However, for the moment we will not integrate it in the main tool, because PanACoTA was developed for rapid analysis of very large datasets. The publication provides running times that are incompatible with the goals of Panacota (several weeks to compute a pan genome of a few hundred genomes). 
However, I created a branch `protein_ortho` in the repository. You can do a pull request to integrate your changes to this branch, so that you can still use it if you have smaller datasets more adapted to this method!

**Pull request closed without merging**
