### PR TITLE
Feature: passing strains list to ncbi-genome-download

### PR DESCRIPTION
**Pull request by oxygen311**
Hello, Amandine!

I've decided to add desired feature by myself :)
I think you can use it as a codebase if you will add this feature to PanACoTA.

It seems to work properly while using `prepare` module itself and in most cases with `all` subcommand. I've even added one unit test for basic functionality.

Possible improvements:
- Strains list while working with `all` subcommand. For some reason it can not handle `-T` and `-S` options together if `-T` contains more then one id. Example: `-T 13373,28450 -S "FMH 23344,6,23344,VB29710"`, downloading only strains from `-T 13373` (works OK with `prepare`). I think it can be because of the requirement of int is some usages of `-T`;
- Also, can be tested with passing file with list of strains to `-S`  instead of list itself.

### CODE REVIEW

**Comment by asetGem** [comment]
Hello!

Thank you for this PR! I have now merged it with the main code, in version 1.3.1-dev1.
I also added some tests and fixed compatibility problems.

As you suggested, I checked that it works fine when giving a file instead of a list of strains.

However, I am not sure to understand your first point. Do you mean that from `prepare` module it does not have the same behaviour as in the `all` module?

**Comment by asetGem** [comment]
As a reminded, this PR is linked to issue #17

**Comment by oxygen311** [comment]
> Thank you for this PR! I have now merged it with the main code, in version 1.3.1-dev1.
> I also added some tests and fixed compatibility problems.

Thank you!

> However, I am not sure to understand your first point. Do you mean that from `prepare` module it does not have the same behaviour as in the `all` module?

Oddly enough, it's actually the way it is.

Command `PanACoTA prepare -T 13373,28450 -S "FMH 23344,6,23344,VB29710" -l 'complete,chromosome'` downloads **4 genomes** from NCBI. Which, I think is expected.

But if you use command `PanACoTA all  -T 13373,28450 -l 'complete,chromosome' -c configfile.ini -o output -n BUMA` and pass `strains = "FMH 23344,6,23344,VB29710"` in config file, **2 genomes** will be downloaded.

**Comment by asetGem** [comment]
Well spotted! thanks for pointing out.

I found the problem. When you put `strains = "FMH 23344,6,23344,VB29710"` in the configfile, it keeps the `"`. So, it is looking for the following strains:
- `"FMH 23344`
- `6`
- `23344`
- `VB29710"`

And this is confirmed when we look at the 2 (out of 4) downloaded files: they do correspond to strains 6 and 23344.

I will add an advice for users to avoid the `"` around parameters in the config file. But I am also adding some code to remove surrounding `"` from all parameters in config file, so that it does not happen again (and somewhere else), even if people use `"`.

**Comment by oxygen311** [comment]
> Well spotted! thanks for pointing out.
> 
> I found the problem. When you put `strains = "FMH 23344,6,23344,VB29710"` in the configfile, it keeps the `"`. So, it is looking for the following strains

Funny bug! :)

Thanks for explaining!
Great, that's everything is working properly.

**Pull request merged**
